# Generated by Django 3.2.13 on 2024-05-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0002_auto_20240527_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='pictures',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='picture_id',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
    ]
