# Generated by Django 3.2.13 on 2024-05-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0005_rename_date_dowload_pictures_date_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocategory',
            name='category_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='picture_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
