# Generated by Django 3.2.13 on 2024-05-27 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0006_auto_20240527_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictures',
            old_name='user_id',
            new_name='user',
        ),
    ]
