# Generated by Django 3.2.13 on 2024-05-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0007_rename_user_id_pictures_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='date_download',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
