# Generated by Django 3.2.13 on 2024-05-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='dasa',
            field=models.TextField(blank=True, db_column='Dasa', null=True),
        ),
    ]
