# Generated by Django 3.2.13 on 2024-05-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_dasa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='dasa',
        ),
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users_images'),
        ),
    ]
